### ISSUE TITLE
[Traefik Plugin Catalog] Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [WagnerPMC/reverseguard#1]
The plugin was not imported into Traefik Plugin Catalog.

Cause:
```
failed to run the plugin with Yaegi: plugin: failed to decode configuration: 1 error(s) decoding:

* 'map[0][dynamic_cidrs]' expected a map, got 'slice'
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.traefik.io/).

**Comment by WagnerPMC** [comment]
Resolved.
